name: cms_flutter_app
description: A cross-platform Canteen Management System for Android and iOS.

publish_to: 'none'  # Remove if publishing.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6

  # API & Networking
  http: ^1.1.0  # Basic API calls
  dio: ^5.4.0   # Advanced HTTP with interceptors (preferred over http)

  # State Management
  provider: ^6.1.1  # Simple state (for Auth, Cart)
  flutter_bloc: ^8.1.3  # For complex state (Orders, Menu)
  equatable: ^2.0.5  # Equality for Bloc states

  # Payments
  razorpay_flutter: ^1.3.7  # Razorpay integration (use stripe_flutter for Stripe)

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3  # Optional: For email/OTP if not using backend
  firebase_messaging: ^14.7.10  # Push notifications
  cloud_firestore: ^4.13.6  # Optional: Direct DB if needed, but prefer backend APIs

  # UI & Utils
  pdf: ^3.10.7  # Client-side PDF bill generation
  printing: ^5.12.0  # Share/print PDFs
  shared_preferences: ^2.2.2  # Store tokens, FCM, role
  go_router: ^12.1.3  # Role-based navigation
  intl: ^0.18.1  # Date/currency formatting
  image_picker: ^1.0.4  # Upload menu images
  flutter_local_notifications: ^16.3.2  # In-app FCM notifications
  permission_handler: ^11.1.0  # Permissions for camera/gallery

  # UI Enhancements (optional)
  flutter_spinkit: ^5.2.0  # Loading animations
  cached_network_image: ^3.3.1  # Image caching for menus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Linting rules

flutter:
  uses-material-design: true

  # Assets (add your icons, images)
  assets:
    - assets/images/
    - assets/icons/