// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1DSR4a60j-Zy06VHyQMg_7jnqcSxWXY',
    appId: '1:864159134910:web:90abb390bdfcb59f541aef',
    messagingSenderId: '864159134910',
    projectId: 'canteen-085',
    authDomain: 'canteen-085.firebaseapp.com',
    storageBucket: 'canteen-085.firebasestorage.app',
    measurementId: 'G-P4XGEV1WV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwThUgahxyVX97V8ylZn47Hy3UrFzrLp4',
    appId: '1:864159134910:android:2a9b06214359bdbf541aef',
    messagingSenderId: '864159134910',
    projectId: 'canteen-085',
    storageBucket: 'canteen-085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrZRXGHbJ1j872OdXEenSQFHDzcXtSzc',
    appId: '1:864159134910:ios:0bfc771f46e1c205541aef',
    messagingSenderId: '864159134910',
    projectId: 'canteen-085',
    storageBucket: 'canteen-085.firebasestorage.app',
    iosBundleId: 'com.example.canteenProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrZRXGHbJ1j872OdXEenSQFHDzcXtSzc',
    appId: '1:864159134910:ios:0bfc771f46e1c205541aef',
    messagingSenderId: '864159134910',
    projectId: 'canteen-085',
    storageBucket: 'canteen-085.firebasestorage.app',
    iosBundleId: 'com.example.canteenProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1DSR4a60j-Zy06VHyQMg_7jnqcSxWXY',
    appId: '1:864159134910:web:870388c5449f55c9541aef',
    messagingSenderId: '864159134910',
    projectId: 'canteen-085',
    authDomain: 'canteen-085.firebaseapp.com',
    storageBucket: 'canteen-085.firebasestorage.app',
    measurementId: 'G-GLK1QWL22Q',
  );
}
